### ISSUE TITLE
Support for Vector devices

### ISSUE THREAD

**Issue by gcShyam** [richClubb/python-lin#4]
I don't see any support for Vector devices.
Is there any plan to add it in the near future?

**Comment by richClubb** [comment]
It was my intention but I no longer have any access to vector hardware so its not likely for the time being.  I did have some ideas to go and work on it with a company I used to work for but due to being in lockdown this isn't possible.

What is your timeframe?

**Comment by gcShyam** [comment]
Because of the lockdown, my time frame is actually until after the lockdown.
Also, is/will there be any documentation for this library?

**Comment by richClubb** [comment]
Yes there will :) The intention is to add python-can like support for LIN devices. It was written because of python-uds and this version is a bit of a hack just to get things working for the project we were doing as we needed UDS over LIN

**Comment by gcShyam** [comment]
Waiting for the packages to be updated for Vector devices.
I hope you will be able to do it soon :)
